//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SocialMedia
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public string Link { get; set; }
        public System.DateTime AddDate { get; set; } 
        public bool isDeleted { get; set; }
        [Column("DeletedDate")]

        public Nullable<System.DateTime> DeleteDate { get; set; } 

        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; } 

        public virtual T_User T_User { get; set; }

    }
}
